# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40954f884614b61873b802d7b37bf91d15f0c63f52a795b4334cf3a5a0738740a41b77927e02f079017f61867f995ea88381a57f89e1a98ef630074f0e5007d5

test:
  secret_key_base: 74b072f547179ca79a2230c43e63fe0c0ac31ad0a3efa3e861baefc7da2de1f239f10f20f15138a798246845f4ad57b4ea035545591da59ca1eefa4c25cdaa2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  google_analytics_code: YOUR CODE HERE
  host: YOUR PRODUCTION HOST URL/IP HERE
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>